spring:
    datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=mydb
      username: sa
      password: ##########
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:  
      show-sql: true
      hibernate:
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            ddl-auto: update
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl